version: '3.8'

networks:
  {{ cookiecutter.project_name }}_net:
    name: {{ cookiecutter.project_name }}_net
    driver: bridge

services:
  backend:
    image: {{cookiecutter.docker_image_backend}}:${DOCKER_TAG:-latest}
    build: ./backend
    container_name: {{cookiecutter.docker_image_backend}}-dev
    restart: always
    ports:
      - "${PORT}:5000"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/backend
    {%- if cookiecutter.use_db == "yes" %}
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    {%- endif %}
    command: > 
      bash -c "flask run --debug -p 5000 --host=${HOST};"
    networks:
      - {{ cookiecutter.project_name }}_net

{%- if cookiecutter.use_db == "yes" %}

  postgres:
    image: postgres:latest
    container_name: {{cookiecutter.docker_image_backend}}-dev-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
      - {{ cookiecutter.project_name }}_net

volumes:
  postgres_data:

{%- endif %}